// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOEigt-VUMlHDhiRi6K4SctM4DCLKfsHA',
    appId: '1:916019610293:android:976f5a0e799fd79115b4fc',
    messagingSenderId: '916019610293',
    projectId: 'mycvapp-fbced',
    databaseURL: 'https://mycvapp-fbced-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mycvapp-fbced.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-PmX_09e9JrRlvKB0PscT-3QC6HYHs1M',
    appId: '1:916019610293:web:96f37f14bef484c115b4fc',
    messagingSenderId: '916019610293',
    projectId: 'mycvapp-fbced',
    authDomain: 'mycvapp-fbced.firebaseapp.com',
    databaseURL: 'https://mycvapp-fbced-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mycvapp-fbced.firebasestorage.app',
    measurementId: 'G-FDKS0Z14FJ',
  );

}